jobs:
   integration-tests:
    name: Integration Tests

    run_when: &DEFAULT_TRIGGERS
      any branch matches:
        type: branch
        include_match: ^.+$
        exclude_match: ^.*(no-ci|hotspot).*$

    context:
      task_defaults:
        traits:
          ci-g2018-03: yes # TEMP!
          vagrant: yes
          virtualbox: yes

      include:
        - path: cider-ci/integration-tests.yml
          submodule: [integration-tests]
